#+TITLE:  General Notes for the Helpers
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2015 Sep 07
#+TAGS:   emacs

This /page/ will serve as the temporary online brainstorming session
of the *PDX Emacs Hackers: Board of Helpers*.

* Description

  The following could be used when advertising the Meetup:

  #+BEGIN_QUOTE
  We get together to share our exciting new discoveries about Emacs and
  its multitudinous ecosystem. We also offer assistance to those who
  have brought Emacs questions along.

  Both Emacs wizards and Emacs novices are welcome. Even Vim users are
  welcome, but we cannot guarantee they will want to remain Vim users at
  the end of the session.
  #+END_QUOTE

  Yes, this was graciously stolen from the London Emacs Hackers group,
  upon which we take our inspiration.


* Immediate Tasks

 - [ ] Collect people for the "Board of Helpers"
   - Howard Abrams
   - Chris Freeman
   - Gary Klimowicz
 - [X] Move documentation to a Git repository
 - [ ] Register the Meetup
   - Need to finalize /the message/
 - [ ] Decide on a location
   - First Meeting: [[http://www.wweek.com/portland/article-21651-the_upper_lip_loose_lips_take_sips.html][Upper Lip of Bailey's Taproom]]
     213 SW Broadway, Portland, OR 97205
     (503) 295-1004
 - [ ] Figure out the best monthly meeting day
   - Sunday afternoon? Not if we use Bailey’s ;-)
   - Wed evening?
   - Brief analysis of [[http://calagator.org/][Calagator]]:
     - Every day has something...
     - Choose a day good for the Board of Helpers at first
 - [ ] Organize the first meeting:
   - Sept 30th at 6:00pm

* Typical Meeting Agenda

  As was mentioned at EmacsConf, having an /default/ meeting format
  will help meet expectations. Here an initial outline idea:

  1. Introductions
  2. Session 1
  3. Lightning Talks
  4. Session 2
  5. Rinse and repeat steps 3 and 4
  6. Question and Answers and General Office Hours

  My concern is placing the burden of a 45 minute presentation on any
  single person’s shoulders (not to mention to keep the audience
  participation high), so we may want to have a two or three shorter
  demonstrations (10-15 minutes). This would allow us to show off the
  new features of Magit, or configuration for editing Ruby, etc.

  I would love to have one or more “lightning talks” of 2-7 minutes
  on a short, cool feature that someone has learned. If we mention
  this beforehand, the audience may come prepared, and these may be
  quite good.

  Once we are done with everything that is prepared, we could have
  “Office Hours” where members with questions or problems can find
  people who could answer them.

* Session Ideas

  We could come up with a list of the “sessions” of topics that could
  be covered during a 10-15 “demonstration”:

  - Magit
    - a general workflow, and/or:
    - new 2.0 features
  - Emacs Configuration for particular languages (we could then
    invite that respective use group community to attend), for instance:
    - Python
    - Ruby
    - Clojure
    - Go
  - org-mode Spreadsheets

*  Repository Ideas

  This repository could become more than just our initial brainstorm,
  but could allow us to collection resources for our members,
  including:

    - resource references and cheatsheets
    - .emacs basics
    - newbie getting started info

  Perhaps we use the standard =org-mode= publish feature to export a
  collection of files to a website. Baby steps, eh?
