#+TITLE:  Second Org Sandbox
#+AUTHOR: (your name)
#+EMAIL:  (your email)
#+DATE:   2016 Jan 20
#+TAGS:   orgmode

* Text Paragraphs

  To help identify paragraphs and their sub-section, the left-side can
  be indented with spaces to line up with header. Both =TAB= and =M-q=
  works as *expected*.

Play around with formatting this paragraph.
Sed bibendum. Integer placerat tristique nisl. Etiam laoreet quam sed arcu. Vivamus id enim.
Nunc porta vulputate tellus.
Fusce commodo.
Nullam rutrum.  Phasellus at dui in ligula mollis ultricies.  Mauris ac felis vel velit tristique imperdiet.

* Some Lists

  - Donec pretium posuere tellus.
  - Etiam laoreet quam sed arcu.
  - Phasellus at dui in ligula mollis ultricies.
  - Donec pretium posuere tellus.
  - Nullam libero mauris, consequat quis, varius et, dictum id, arcu.
  - Nullam tempus.
  - Nullam tempus.
  - Donec pretium posuere tellus.
  - Donec vitae dolor.
  - Etiam laoreet quam sed arcu.

* Tables

  Here is a table:

  | Bottle | Distillery | Date |
  |-

* Blocks

  Here are some blocked structure to play with:

  #+BEGIN_QUOTE
     To quote someone or something is divine.
  #+END_QUOTE

  Type TAB on the "BEGIN" line to collapse it.

  #+BEGIN_EXAMPLE
     To quote someone or something is divine.
  #+END_EXAMPLE

  Especially source code (notice the language mode):

  #+BEGIN_SRC ruby
    [1, 2, 3, 5, 7, 11, 13].each do |prime|
       puts prime
    end
  #+END_SRC

  Type C-c and then ' to edit the source code block in a ruby buffer.
  Type C-x C-s to return.
